### PR TITLE
Expose target to make comlink compatible  with proxy-polyfill

### PR DESCRIPTION
**Pull request by frannunezrivera**
Hi there,

Right now comlink doesn't work with proxy-polyfill. This is because **proxy-polyfill** seals the object when creates the proxy and properties can't be added afterwards and **comlink** wrap function always creates the Proxy with an empty function as target.

I've checked project history and this was once addressed ( in this PR 
 https://github.com/GoogleChromeLabs/comlink/pull/113/files ) but somehow changes were lost after a big update. 

It's a very little change, Do you think is possible to add it again? I have tested using comlink with proxy-polyfills on IE11 and it just works :)

PS. I'm not very familiar with TS, let me know if I missed something.

Thanks!

### CODE REVIEW

**Comment by frannunezrivera** [comment]
@googlebot I signed it!

**Comment by surma** [comment]
Thank you, @frannunezrivera!

**Comment by frannunezrivera** [comment]
Great! Thanks to you @surma  :)

**Comment by sdyalor** [comment]
@frannunezrivera Can you please give an example webpack or rollup, to get comlink with IE11?
I've been trying since I read your post but no success ;'c
With webpack, I have this.
index.js
```
import 'proxy-polyfill/proxy.min.js';
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import 'whatwg-fetch';
import {wrap} from 'comlink/dist/umd/comlink';

 async function init() {
   const worker = new Worker('./my.worker.js', {type: 'module'});
   // WebWorkers use `postMessage` and therefore work with Comlink.
   const obj = wrap(worker);
   alert(`Counter: ${await obj.counter}`);
   await obj.inc();
   alert(`Counter: ${await obj.counter}`);
}
init();
```
my.worker.js
```
import 'proxy-polyfill/proxy.min.js';
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import 'whatwg-fetch';
// import 'core-js/es/symbol';
// import 'core-js/es/weak-set';
import {expose, wrap } from 'comlink/dist/esm/comlink.min.js';

const obj = {
  counter: 0,
  inc() {
    this.counter++;
  }
};

expose(obj);
```
Alert returns counter as undefined ;'c

**Comment by frannunezrivera** [comment]
hey @sdyalor,

I won't give you an example, but I can let you know what are you missing to make it work. :)

First, the latest changes (where my PR is included) haven't been released as the npm package, so if you are using comlink using `npm install` it won't work. (you better clone master and build your own version for now).

Second, the main issue I see in the code you've posted is when you call the wrap method 
`const obj = wrap(worker);`

**proxy-polyfill** [seals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) the Proxy object once created so you need to define the functions to be exposed when wrapping. Content of the object properties can change but you can't add/remove properties to/from a sealed object.

To fix the example you posted, you can do basically....
```
const obj = {
  counter: {},
  inc: {}
};
const obj = wrap(worker, obj);
```

The rest of your code looks fine to me.

Regards

**Comment by sdyalor** [comment]
@frannunezrivera I'll try it out, Thank you so much for quick response

**Comment by sdyalor** [comment]
@frannunezrivera  I built the master branch then. wow, ahmm no errors but (chrome is fine as always)
Now It Returns a function
image
```index.js
import 'proxy-polyfill/proxy.min.js';
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import {wrap} from '../comlink/dist/umd/comlink';
async function init() {
   const worker = new Worker('./my.worker.js', {name: 'myWorky', type: 'module'});
   // WebWorkers use `postMessage` and therefore work with Comlink.
   const obj = {
	counter: {},
	inc: {}
  };
  const obj2 = wrap(worker, obj);
   alert(`Counter: ${await obj2.counter}`);
   await obj2.inc();
   alert(`Counter: ${await obj2.counter}`);
}
init();
```
```worker.js
import 'proxy-polyfill/proxy.min.js';
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import 'whatwg-fetch';
import {expose} from '../comlink/dist/umd/comlink';

const obj = {
  counter: 0,
  inc() {
    this.counter++;
  }
};
expose(obj);
```
maybe my webpack.conf.js?
```
const CopyWebpackPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WorkboxWebpackPlugin = require('workbox-webpack-plugin');
const path = require('path');
const webpack = require('webpack');
const WorkerPlugin = require('worker-plugin');

const extensions = ['.js', '.jsx', '.ts', '.tsx','.mjs'];
const babelRc = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
        targets: {
          ie: 11
        },
        useBuiltIns: 'entry',
        corejs: 3,
        debug: true
      }
    ],
    '@babel/preset-typescript'
  ],
  plugins: [
    ['babel-plugin-const-enum'],
    ['@babel/plugin-syntax-dynamic-import'],
    [
      '@babel/plugin-proposal-decorators',
      { decoratorsBeforeExport: true }
    ],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    // ['babel-plugin-transform-async-to-promises'],
    ["@babel/plugin-transform-arrow-functions", { "spec": true }],
    ['@babel/plugin-transform-template-literals']
  ]
  // ignore: [
  //   // 'node_modules/proxy-polyfill'
  // ]
};

module.exports = {
  devtool: 'source-map',
  devServer: {
    historyApiFallback: true
  },
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.(ts|js|mjs)x?$/,
        exclude: [
          /@babel(?:\/|\\{1,2})runtime|core-js/,
          /regenerator-runtime/,
          /proxy-polyfill/
        ],
        use: [
          // {
          //   loader: 'thread-loader',
          //   options: {}
          // },
          // {
          //   loader: 'cache-loader'
          // },
          {
            loader: 'babel-loader',
            options: babelRc
          }
        ]
      },
      {
        test: /\.html$/,
        loader: 'html-loader'
      }
    ]
  },
  resolve: {
    extensions
  },
  plugins: [
    new CopyWebpackPlugin([
      // 'images/**',
      // 'node_modules/@webcomponents/webcomponentsjs/**',
      // 'manifest.json'
      // 'index.html'
    ]),
    new HtmlWebpackPlugin({
      chunksSortMode: 'none',
      template: 'index.html'
    }),
    // new WorkboxWebpackPlugin.GenerateSW({
    //   include: ['index.html', 'manifest.json', /\.js$/],
    //   exclude: [/\/@webcomponents\/webcomponentsjs\//],
    //   navigateFallback: 'index.html',
    //   swDest: 'service-worker.js',
    //   clientsClaim: true,
    //   skipWaiting: true,
    //   runtimeCaching: [
    //     {
    //       urlPattern: /\/@webcomponents\/webcomponentsjs\//,
    //       handler: 'staleWhileRevalidate'
    //     },
    //     {
    //       urlPattern: /^https:\/\/fonts.gstatic.com\//,
    //       handler: 'staleWhileRevalidate'
    //     }
    //   ]
    // })
    new WorkerPlugin(
      {
        // disable warnings about "window" breaking HMR:
        globalObject: false
      }
    )

  ]
};
```

**Comment by frannunezrivera** [comment]
Hey @sdyalor ,

I'm sorry but I can't help you anymore, you'll have to find out by yourself.
Anyway it looks better. 
My two cents... In cases like this, I like to isolate the code where I'm having issues. Remove webpack and any other libraries and use plain JS with the libraries involved (comlink and proxy-polyfill) and start from there.

Regards and good luck!

**Comment by sdyalor** [comment]
@frannunezrivera I'v got some success 
image
In this picture we can see the counter updated by setInterval in the mainThread
```
async function init() {
  // WebWorkers use `postMessage` and therefore work with Comlink.
  const worker = new Worker('dist/my.worker.js');
  const obj = {
    getCounter: {},
    counter: 0,
    inc: {}
  };
  const obj2 = Comlink.wrap(worker, obj);
  //  alert(`Counter: ${await obj2.counter}`);
  //  await obj2.inc();
  //  alert(`Counter: ${await obj2.counter}`);
  setInterval(async x => await obj2.inc(), 2000);
  setInterval(async x => console.log("from main this is counter from getCounter", await obj2.getCounter()), 2000);
  setInterval(async x => console.log("from main this is counter from counter", await obj2.counter), 2000);
}
init();

```
but 
I dont know how proxy-polyfill does
Your advice was right but just works with functions ;'c in the object, not properties ;'c


> To fix the example you posted, you can do basically....
> 
> ```
> const obj = {
>   counter: {},
>   inc: {}
> };
> const obj = wrap(worker, obj);
> ```

I'v done this with rollup and updated the example https://github.com/sdyalor/comlink.pwa
Help UwU

**Pull request merged**
