### PR TITLE
Detect TypedArray.buffer is Transferable

### PR DESCRIPTION
**Pull request by 3846masa**
TypedArray.prototype.buffer is ArrayBuffer, so it is Transferable.
However, because of `iterateAllProperties` skips TypedArray, TypedArray.prototype.buffer won't be detected as Transferable.

This PR enable to detect Transferable in TypedArray.

### CODE REVIEW

**Comment by surma** [comment]
Hey @3846masa,

I don’t think this patch is correct. I have [tests](https://github.com/GoogleChromeLabs/comlink/blob/master/tests/same_window.comlink.test.js#L292-L301) that test that buffers will be transferred.

TypedArrays, on the other hand, are _not_ transferable (only their underlying buffers are). So Comlink shouldn’t transfer them, either.

For example, this piece of code:
```js
const {port1, port2} = new MessageChannel()
port2.onmessage = ev => console.log(ev.data);
ta = new Uint8Array([1, 2, 3]);
port1.postMessage(ta, [ta]);
```

will error with `Uncaught TypeError: Failed to execute 'postMessage' on 'MessagePort': Value at index 0 does not have a transferable type.`

**Comment by 3846masa** [comment]
@surma Thanks for replying.
But, You mistaken about this PR, I think.

This PR allow to pass `TypedArray.prototype.buffer`, not `TypedArray` self.

Your sample code is wrong. The following code works on Chrome.
```js
const {port1, port2} = new MessageChannel()
port2.onmessage = ev => console.log(ev.data);
ta = new Uint8Array([1, 2, 3]);
port1.postMessage(ta, [ta.buffer]);
```

Please reconsideration it.

**Comment by surma** [comment]
You are absolutely correct. Thanks for correcting me.

I think the PR looks good, but do you mind adding a test so we don’t regress on this in the future?

**Comment by 3846masa** [comment]
Ok, I'll add tests for this.

**Comment by 3846masa** [comment]
Is it necessary to build before testing?

**Comment by surma** [comment]
The test doesn’t seem to pass currently :(

**Comment by surma** [comment]
Yes, it’s necessary to build. The tests don’t run TypeScript, but rather the compiled JavaScript.

**Pull request merged**
