### PR TITLE
This might be a solution for #474

### PR DESCRIPTION
**Pull request by MrMadClown**
#474 
- changed WireValueType and MessageType to strings
- added a default branch in expose switch

### CODE REVIEW

**Comment by MrMadClown** [comment]
@googlebot I signed it!

**Comment by MrMadClown** [comment]
@surma got a Tip for me whats wrong with the Tests? i don't get it.

**Comment by Qendolin** [comment]
The test is failing because of your formatting. Run `npm run fmt` and if that does not work just replace the single quotes with double quotes.

**Comment by DataBound** [comment]
Any news about this? I got the same issue and that fixed it

**Comment by MrMadClown** [comment]
@surma is there anything inherently wrong with this?

**Comment by updatedData** [comment]
Just what I'm looking for thanks @MrMadClown

**Comment by pm-harshad-mane** [comment]
@MrMadClown waiting for your PR to merge.

**Comment by pm-harshad-mane** [comment]
@MrMadClown , so with this PR a worker will also be able to call a method on main, right?
Can you please add an example too?

**Comment by MrMadClown** [comment]
@pm-harshad-mane 
It's already possible, but you might experience Exception ping pong, since the `MessageTypes/WireValueType` enums overlap. (See #474)
[here is a sample Repository](https://github.com/MrMadClown/comlink-iframe-2-way-example)

**Comment by Qendolin** [comment]
I don't see why this isn't merged already. It's a very simple change for something that is clearly a bug.

**Comment by pm-harshad-mane** [comment]
@surma , can you please merge this PR?

**Comment by updatedData** [comment]
@surma do you need anything else for this to be accepted?

**Comment by surma** [comment]
Hey all.

Sorry for taking, uh, half a year to get back to this. I couldn’t commit a lot of time to OSS maintenance. Hope y’all understand.

The PR looks good to me, but I’d want to also add tests. 

@MrMadClown I know it’s been ages, but are you still up for adding tests? Otherwise I’ll do it whenever I get around to it.

**Comment by MrMadClown** [comment]
@surma For the `default` case? Sure I could try to put together a Testcase.

**Comment by surma** [comment]
I meant a test that uses iFrames on both sides, as outlined in #474

**Comment by MrMadClown** [comment]
@surma Is the Test I added something like you had in mind?

**Comment by pm-harshad-mane** [comment]
@surma tests are added, could you please review?

**Review by surma — APPROVED** [review]
Cheers for the test. This looks great.

**Pull request merged**
